export const ACTIVITY_BAR_WIDTH = 48
export const MIN_SIDEBAR_WIDTH = 140
export const DEFAULT_SIDEBAR_WIDTH = 180
export const MIN_TODO_WIDTH = 420

export const MIN_MAIN_WINDOW_WIDTH = ACTIVITY_BAR_WIDTH + MIN_SIDEBAR_WIDTH + MIN_TODO_WIDTH
